name: Generate Permanent Keystore Base64

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Keystore & Print Base64
        run: |
          keytool -genkeypair -alias mykeyalias -keyalg RSA -keysize 2048 -validity 10000 \
            -keystore upload-keystore.jks \
            -storepass 12345678 -keypass 12345678 \
            -dname "CN=Developer, OU=Dev, O=App, L=City, S=State, C=TR"
          
          echo "=========================================="
          echo "AŞAĞIDAKİ METNİ KOPYALA VE SECRETS'A EKLE:"
          echo "=========================================="
          base64 -w 0 upload-keystore.jks
          echo ""
          echo "=========================================="
